# Generated by Django 3.1.2 on 2020-12-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('nodes', models.IntegerField(default=0)),
                ('autoSuspend', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('statusOfCluster', models.IntegerField(default=0)),
                ('createdTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastAccessed', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('businessUnit', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('createdTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastAccessed', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('dataOfFlow', models.TextField()),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('lastAccessed', models.DateTimeField(auto_now=True)),
                ('clusterOfFlow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_integration.clustermodel')),
            ],
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='projectOfCluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_integration.projectmodel'),
        ),
    ]
